version: '3.8'
services:

  #PHP Service
  api-1:
    build:
      args:
        user: test
        uid: 1000
      context: ./
      dockerfile:  Dockerfile
    image: digitalocean.com/php
    container_name: api-1
    hostname: api-1
    restart: unless-stopped
    depends_on:
      - db
    tty: true
    env_file:
      - .one.env
    # environment:
    #   SERVICE_NAME: app
    #   SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - webdata:/var/www
       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
  api-2:
    build:
      args:
        user: test
        uid: 1000
      context: ./
      dockerfile:  Dockerfile
    image: digitalocean.com/php
    container_name: api-2
    hostname: api-2
    restart: unless-stopped
    depends_on:
      - db
    tty: true
    env_file:
      - .two.env
    working_dir: /var/www
    volumes:
       - webdata:/var/www
       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  api-proxy:
    image: nginx:alpine
    container_name: api-proxy
    hostname: api-proxy
    restart: unless-stopped
    depends_on:
      - api-1
      - api-2
    ports:
      - "8001:8001"
    tty: true
    volumes:
      - webdata:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: simple_trader
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - api-dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    
  #InfluxDB Service
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    tty: true
    ports:
      - "8086:8086"
    environment:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: admin
        DOCKER_INFLUXDB_INIT_PASSWORD: password
        DOCKER_INFLUXDB_INIT_ORG: simple-trader
        DOCKER_INFLUXDB_INIT_BUCKET: simple-trader
    volumes:
      - influxdbdata:/var/lib/influxdb2

#Docker Networks
networks:
  default:
    name: 'simple-trader'
    external: true

#Volumes
volumes:
  api-dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mysql
  influxdbdata:
    driver: local
  webdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./
