version: '3.5'
services:

  #PHP Service
  api-1:
    build:
      args:
        user: test
        uid: 1000
      context: ./
      dockerfile:  Dockerfile
    image: digitalocean.com/php
    container_name: api-1
    hostname: api-1
    restart: unless-stopped
    depends_on:
      - api-db
    env_file:
      - .one.env
    working_dir: /var/www
    volumes:
       - webdata:/var/www
       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
  api-2:
    build:
      args:
        user: test
        uid: 1000
      context: ./
      dockerfile:  Dockerfile
    image: digitalocean.com/php
    container_name: api-2
    hostname: api-2
    restart: unless-stopped
    depends_on:
      - api-db
    env_file:
      - .two.env
    working_dir: /var/www
    volumes:
       - webdata:/var/www
       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  api-proxy:
    image: nginx:alpine
    container_name: api-proxy
    hostname: api-proxy
    restart: unless-stopped
    depends_on:
      - api-1
      - api-2
    ports:
      - "8002:8002"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - webdata:/var/www

  #MySQL Service
  api-db:
    image: mysql:5.7.22
    container_name: api-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: simple_trader
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - api-dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

#Docker Networks
networks:
  default:
    name: 'simple-trader'
    external: true

#Volumes
volumes:
  api-dbdata:
  webdata: